window.WORDS = [
  {
    "lesson": "1-1",
    "part": "1",
    "en": "Ms.",
    "answer": "Ms.",
    "ipa": "[mɪz]",
    "pos": "名",
    "ja": "〈女性に対して〉〜さん、〜先生",
    "ex_en": "Ms. Nonaka! — Yes?",
    "ex_ja": "野中先生！ — なんですか？",
    "memo": ""
  },
  {
    "lesson": "1-1",
    "part": "1",
    "en": "I'm",
    "answer": "I'm",
    "ipa": "[aɪm]",
    "pos": "短",
    "ja": "I am の短縮形",
    "ex_en": "I'm hungry.",
    "ex_ja": "おなかへった。",
    "memo": ""
  },
  {
    "lesson": "1-1",
    "part": "1",
    "en": "often",
    "answer": "often",
    "ipa": "[ˈɔːfən]",
    "pos": "副",
    "ja": "よく",
    "ex_en": "My brother often reads manga in the bathroom.",
    "ex_ja": "うちの兄はよくトイレでマンガを読んでいます。",
    "memo": ""
  },
  {
    "lesson": "1-1",
    "part": "1",
    "en": "be good at 〜",
    "answer": "be good at ",
    "ipa": "[—]",
    "pos": "句",
    "ja": "〜が上手である",
    "ex_en": "Oh, you are good at drawing camels.",
    "ex_ja": "わ、ラクダの絵描くの上手。",
    "memo": ""
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "fan",
    "answer": "fan",
    "ipa": "[fæn]",
    "pos": "名",
    "ja": "ファン",
    "ex_en": "I'm not a fan of soccer.",
    "ex_ja": "サッカーは好きじゃないの。",
    "memo": ""
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "every",
    "answer": "every",
    "ipa": "[ˈevri]",
    "pos": "形",
    "ja": "どの〜も、毎〜",
    "ex_en": "Gah, every unit has new words to learn.",
    "ex_ja": "もー、どの単元にも新出単語があるー。",
    "memo": ""
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "every day",
    "answer": "every day",
    "ipa": "[—]",
    "pos": "句",
    "ja": "毎日",
    "ex_en": "Do 50 sit-ups every day!",
    "ex_ja": "毎日腹筋50回だ！",
    "memo": ""
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "don't",
    "answer": "don't",
    "ipa": "[doʊnt]",
    "pos": "短",
    "ja": "do not の短縮形",
    "ex_en": "Oh, don't open that! — Why?",
    "ex_ja": "あ、それ開けちゃだめ！ — なんで？",
    "memo": ""
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "after",
    "answer": "after",
    "ipa": "[ˈæftər]",
    "pos": "前",
    "ja": "〜のあとに",
    "ex_en": "Please leave your message after the beep.",
    "ex_ja": "発信音のあとにメッセージをどうぞ。",
    "memo": "反対はbefore（～の前に）"
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "after school",
    "answer": "after school",
    "ipa": "[—]",
    "pos": "句",
    "ja": "放課後",
    "ex_en": "I practice tennis almost every day after school.",
    "ex_ja": "放課後はほとんど毎日テニスを練習しています。",
    "memo": ""
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "hip-hop",
    "answer": "hip-hop",
    "ipa": "[ˈhɪp hɑːp]",
    "pos": "名",
    "ja": "〈音楽の〉ヒップホップ",
    "ex_en": "I sometimes listen to hip-hop, too.",
    "ex_ja": "ヒップホップもたまに聞くよ。",
    "memo": ""
  },
  {
    "lesson": "1-2",
    "part": "2",
    "en": "dancer",
    "answer": "dancer",
    "ipa": "[ˈdænsər]",
    "pos": "名",
    "ja": "踊る人",
    "ex_en": "This actor is a good singer and dancer.",
    "ex_ja": "この俳優さん歌もダンスもうまいよね。",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "rock",
    "answer": "rock",
    "ipa": "[rɑːk]",
    "pos": "名",
    "ja": "〈音楽の〉ロック",
    "ex_en": "Do you know U2? The Irish rock band.",
    "ex_ja": "U2って知ってる？ アイルランドのロックバンドの。",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "action",
    "answer": "action",
    "ipa": "[ˈækʃən]",
    "pos": "名",
    "ja": "動作",
    "ex_en": "\"Play\" is an action verb, and \"like\" is a state verb.",
    "ex_ja": "「play」は動作動詞、「like」は状態動詞です。",
    "memo": "動詞はact（行動する）"
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "anime",
    "answer": "anime",
    "ipa": "[ˈænəmi]",
    "pos": "名",
    "ja": "〈日本の〉アニメ",
    "ex_en": "I love the main theme song of this anime.",
    "ex_ja": "このアニメの主題歌がめっちゃ好き。",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "manga",
    "answer": "manga",
    "ipa": "[ˈmæŋgə]",
    "pos": "名",
    "ja": "〈日本の〉マンガ",
    "ex_en": "I really like this manga artist.",
    "ex_ja": "この漫画家さんすごい好き。",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "weekend",
    "answer": "weekend",
    "ipa": "[ˈwiːkend]",
    "pos": "名",
    "ja": "週末",
    "ex_en": "Have a nice weekend. — Thanks. You too.",
    "ex_ja": "よい週末を。 — ありがとう。きみもね。",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "at home",
    "answer": "at home",
    "ipa": "[—]",
    "pos": "句",
    "ja": "家で[に]",
    "ex_en": "Are you at home right now? — I am. What's up?",
    "ex_ja": "今、家にいる？ — いるよ。どうしたの？",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "take a picture",
    "answer": "take a picture",
    "ipa": "[—]",
    "pos": "句",
    "ja": "写真を撮る",
    "ex_en": "Can you take a picture of us?",
    "ex_ja": "私たちの写真を1枚撮ってくれませんか？",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "look at 〜",
    "answer": "look at ",
    "ipa": "[—]",
    "pos": "句",
    "ja": "〜を見る",
    "ex_en": "Okay, look at the blackboard.",
    "ex_ja": "はいー、黒板見てー。",
    "memo": ""
  },
  {
    "lesson": "1-3",
    "part": "3",
    "en": "pet",
    "answer": "pet",
    "ipa": "[pet]",
    "pos": "名",
    "ja": "ペット",
    "ex_en": "I want to have a donkey as a pet.",
    "ex_ja": "ペットにロバを飼いたいです。",
    "memo": ""
  },
  {
    "lesson": "1-4",
    "part": "Goal Activity",
    "en": "love",
    "answer": "love",
    "ipa": "[lʌv]",
    "pos": "動",
    "ja": "愛する",
    "ex_en": "I love boiled eggs.",
    "ex_ja": "ゆで卵大好き。",
    "memo": ""
  },
  {
    "lesson": "1-4",
    "part": "Goal Activity",
    "en": "flavor",
    "answer": "flavor",
    "ipa": "[ˈfleɪvər]",
    "pos": "名",
    "ja": "風味",
    "ex_en": "What flavor is that? — It's rum raisin.",
    "ex_ja": "それ何味？ — ラムレーズン。",
    "memo": "動詞もflavor（風味をつける）"
  },
  {
    "lesson": "1-4",
    "part": "Goal Activity",
    "en": "tablet",
    "answer": "tablet",
    "ipa": "[ˈtæblət]",
    "pos": "名",
    "ja": "平板、タブレット",
    "ex_en": "Oh, I forgot to charge my tablet again.",
    "ex_ja": "あー、またタブレット充電するの忘れてた。",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "firefighter",
    "answer": "firefighter",
    "ipa": "[ˈfaɪərfaɪtər]",
    "pos": "名",
    "ja": "消防士",
    "ex_en": "I wanted to be a firefighter when I was little.",
    "ex_ja": "小さいときは消防士になりたかったんだよね。",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "smile",
    "answer": "smile",
    "ipa": "[smaɪl]",
    "pos": "名",
    "ja": "微笑み",
    "ex_en": "She gave me the okay with a smile!",
    "ex_ja": "笑顔でオッケーくれた！",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "skateboard",
    "answer": "skateboard",
    "ipa": "[ˈskeɪtbɔːrd]",
    "pos": "動",
    "ja": "スケートボードをする",
    "ex_en": "Can you skateboard or snowboard?",
    "ex_ja": "スケボとかスノボとかできる？",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "she's",
    "answer": "she's",
    "ipa": "[ʃiːz]",
    "pos": "短",
    "ja": "she is の短縮形",
    "ex_en": "I invited Yui, but she's busy.",
    "ex_ja": "ユイ誘ったんだけど、忙しいって。",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "popular",
    "answer": "popular",
    "ipa": "[ˈpɑːpjələr]",
    "pos": "形",
    "ja": "人気のある",
    "ex_en": "What songs are popular right now?",
    "ex_ja": "今どんな歌が人気なの？",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "her",
    "answer": "her",
    "ipa": "[hɜːr]",
    "pos": "代",
    "ja": "彼女の",
    "ex_en": "Mayumi looks a lot like her sister.",
    "ex_ja": "マユミはお姉ちゃんとよく似てる。",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "powerful",
    "answer": "powerful",
    "ipa": "[ˈpaʊərfl]",
    "pos": "形",
    "ja": "力強い",
    "ex_en": "Wow, this hair dryer is too powerful!",
    "ex_ja": "わっ、このドライヤーめっちゃ強力！",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "voice",
    "answer": "voice",
    "ipa": "[vɔɪs]",
    "pos": "名",
    "ja": "声",
    "ex_en": "His voice sounds like someone’s.",
    "ex_ja": "彼の声、だれかの声に似てる。",
    "memo": ""
  },
  {
    "lesson": "2-1",
    "part": "1",
    "en": "it's",
    "answer": "it's",
    "ipa": "[ɪts]",
    "pos": "短",
    "ja": "it is の短縮形",
    "ex_en": "Be careful. It’s hot.",
    "ex_ja": "気をつけて。熱いよ。",
    "memo": ""
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "cannot",
    "answer": "cannot",
    "ipa": "[kænɑːt]",
    "pos": "否",
    "ja": "can の否定形",
    "ex_en": "Warning: You cannot access this site right now.",
    "ex_ja": "警告：このサイトにはただいまアクセスできません。",
    "memo": ""
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "can't",
    "answer": "can't",
    "ipa": "[kænt]",
    "pos": "短",
    "ja": "cannot の短縮形",
    "ex_en": "No, no, no, no, I can’t sing in front of people.",
    "ex_ja": "いやいやいやいや、人前では歌えないって。",
    "memo": ""
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "teach",
    "answer": "teach",
    "ipa": "[tiːtʃ]",
    "pos": "動",
    "ja": "教える",
    "ex_en": "Can you teach me this? — All right.",
    "ex_ja": "ここ教えて。 — いいよ。",
    "memo": ""
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "sure",
    "answer": "sure",
    "ipa": "[ʃʊr]",
    "pos": "副",
    "ja": "もちろん",
    "ex_en": "Can I come with you? — Sure.",
    "ex_ja": "おれもいっしょに行っていい？ — いいよ。",
    "memo": ""
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "piece",
    "answer": "piece",
    "ipa": "[piːs]",
    "pos": "名",
    "ja": "1つのかけら、〈将棋などの〉駒",
    "ex_en": "The last piece of the puzzle is missing.",
    "ex_ja": "パズルの最後のピースがどっかいった。",
    "memo": ""
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "move",
    "answer": "move",
    "ipa": "[muːv]",
    "pos": "動",
    "ja": "動かす、動く",
    "ex_en": "I can’t move my shoulder right now.",
    "ex_ja": "今は肩を動かせません。",
    "memo": "名詞はmovement（動き）"
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "space",
    "answer": "space",
    "ipa": "[speɪs]",
    "pos": "名",
    "ja": "空間",
    "ex_en": "You don’t put spaces between words in Japanese.",
    "ex_ja": "日本語では単語と単語の間にスペースを入れません。",
    "memo": ""
  },
  {
    "lesson": "2-2",
    "part": "2",
    "en": "forward",
    "answer": "forward",
    "ipa": "[ˈfɔːrwərd]",
    "pos": "副",
    "ja": "前へ",
    "ex_en": "Can we move the desk forward a little?",
    "ex_ja": "机を少し前に動かしてもいい？",
    "memo": ""
  },
  {
    "lesson": "2-3",
    "part": "Goal Activity",
    "en": "he's",
    "answer": "he's",
    "ipa": "[hiːz]",
    "pos": "短",
    "ja": "he is の短縮形",
    "ex_en": "Where’s Mr. Morita? — He’s off today.",
    "ex_ja": "森田先生はどちらですか？ — 今日はお休みですよ。",
    "memo": ""
  },
  {
    "lesson": "2-3",
    "part": "Goal Activity",
    "en": "uncle",
    "answer": "uncle",
    "ipa": "[ˈʌŋkl]",
    "pos": "名",
    "ja": "おじ",
    "ex_en": "My sister had a baby, so now I’m an uncle.",
    "ex_ja": "姉ちゃんに子どもが生まれたの、だからぼくはもうおじ。",
    "memo": ""
  },
  {
    "lesson": "2-3",
    "part": "Goal Activity",
    "en": "language",
    "answer": "language",
    "ipa": "[ˈlæŋgwɪdʒ]",
    "pos": "名",
    "ja": "言語",
    "ex_en": "Why do over 7,000 languages exist?",
    "ex_ja": "なんで7,000以上も言語が存在するの？",
    "memo": ""
  },
  {
    "lesson": "2-3",
    "part": "Goal Activity",
    "en": "his",
    "answer": "his",
    "ipa": "[hɪz]",
    "pos": "代",
    "ja": "彼の",
    "ex_en": "He is so good. I want to have his talent.",
    "ex_ja": "あいつめっちゃ上手いな。あいつの才能がほしい。",
    "memo": ""
  },
  {
    "lesson": "2-3",
    "part": "Goal Activity",
    "en": "Chinese",
    "answer": "Chinese",
    "ipa": "[ˌtʃaɪˈniːz]",
    "pos": "名",
    "ja": "中国語",
    "ex_en": "I want to be able to speak Chinese.",
    "ex_ja": "中国語話せるようになりたいな。",
    "memo": ""
  },
  {
    "lesson": "3-1",
    "part": "Introduction",
    "en": "treasure",
    "answer": "treasure",
    "ipa": "[ˈtreʒər]",
    "pos": "名",
    "ja": "宝物",
    "ex_en": "Life itself is a treasure.",
    "ex_ja": "命どう宝。",
    "memo": "沖縄のことば"
  },
  {
    "lesson": "3-1",
    "part": "Introduction",
    "en": "camera",
    "answer": "camera",
    "ipa": "[ˈkæmərə]",
    "pos": "名",
    "ja": "カメラ",
    "ex_en": "Look straight into the camera.",
    "ex_ja": "カメラ目線でお願いします。",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "open",
    "answer": "open",
    "ipa": "[ˈoʊpən]",
    "pos": "動",
    "ja": "開ける、開く",
    "ex_en": "Please open and close the door quietly.",
    "ex_ja": "ドアの開け閉めはお静かに。",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "o'clock",
    "answer": "o'clock",
    "ipa": "[əˈklɑːk]",
    "pos": "副",
    "ja": "〜時",
    "ex_en": "I have a reservation for 8 o'clock.",
    "ex_ja": "8時に予約した者です。",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "that's",
    "answer": "that's",
    "ipa": "[ðæts]",
    "pos": "短",
    "ja": "that is の短縮形",
    "ex_en": "Hey! That's my ice cream!",
    "ex_ja": "ちょっと！ それ私のアイス！",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "isn't",
    "answer": "isn't",
    "ipa": "[ˈɪznt]",
    "pos": "短",
    "ja": "is not の短縮形",
    "ex_en": "That isn't a chair.",
    "ex_ja": "それイスじゃないよ。",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "we're",
    "answer": "we're",
    "ipa": "[wɪr]",
    "pos": "短",
    "ja": "we are の短縮形",
    "ex_en": "Our ball hit your car. We're sorry.",
    "ex_ja": "先生の車にボールをぶつけてしまいました。ごめんなさい。",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "gate",
    "answer": "gate",
    "ipa": "[geɪt]",
    "pos": "名",
    "ja": "門",
    "ex_en": "There's a tiny cat on top of the gate.",
    "ex_ja": "門の上にちびねこがいる。",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "scary",
    "answer": "scary",
    "ipa": "[ˈskeri]",
    "pos": "形",
    "ja": "こわい",
    "ex_en": "The interviewer was so scary.",
    "ex_ja": "面接官めっちゃこわかった。",
    "memo": ""
  },
  {
    "lesson": "3-2",
    "part": "1",
    "en": "statue",
    "answer": "statue",
    "ipa": "[ˈstætʃuː]",
    "pos": "名",
    "ja": "像",
    "ex_en": "A statue stands at the entrance of the school.",
    "ex_ja": "学校の入り口に銅像が立っています。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "dictionary",
    "answer": "dictionary",
    "ipa": "[ˈdɪkʃəneri]",
    "pos": "名",
    "ja": "辞書",
    "ex_en": "A dictionary is not a pillow.",
    "ex_ja": "辞書は枕ではありません。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "blackboard",
    "answer": "blackboard",
    "ipa": "[ˈblækbɔːrd]",
    "pos": "名",
    "ja": "黒板",
    "ex_en": "Can I erase the blackboard? — Hold on.",
    "ex_ja": "黒板消してもいい？ — 待って。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "you're",
    "answer": "you're",
    "ipa": "[jʊr]",
    "pos": "短",
    "ja": "you are の短縮形",
    "ex_en": "Wow, you're so kind. Thank you.",
    "ex_ja": "わー優しい。ありがとう。",
    "memo": "your（あなたの）と同じ発音"
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "correct",
    "answer": "correct",
    "ipa": "[kəˈrekt]",
    "pos": "形",
    "ja": "〈答えや情報などが〉正確な",
    "ex_en": "Both are correct!",
    "ex_ja": "両方とも正解！",
    "memo": "反対はincorrect（不正解な）"
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "almost",
    "answer": "almost",
    "ipa": "[ˈɔːlmoʊst]",
    "pos": "副",
    "ja": "ほとんど",
    "ex_en": "Uh-oh. The gas is almost empty.",
    "ex_ja": "しまった。ガソリンがほとんど空っぽだ。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "wrong",
    "answer": "wrong",
    "ipa": "[rɔːŋ]",
    "pos": "形",
    "ja": "〈本来から外れて〉まちがった",
    "ex_en": "Oh, I got off at the wrong station.",
    "ex_ja": "あ、ちがう駅で降りちゃった。",
    "memo": "反対はright（正しい）"
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "Indian",
    "answer": "Indian",
    "ipa": "[ˈɪndiən]",
    "pos": "形",
    "ja": "インドの",
    "ex_en": "I like both Indian curry and Japanese curry.",
    "ex_ja": "インドのカレーも日本のカレーもどっちも好き。",
    "memo": "名詞はIndia（インド）"
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "what's",
    "answer": "what's",
    "ipa": "[wʌts]",
    "pos": "短",
    "ja": "what is の短縮形",
    "ex_en": "What's in cola?",
    "ex_ja": "コーラって何が入ってるの？",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "traditional",
    "answer": "traditional",
    "ipa": "[trəˈdɪʃənl]",
    "pos": "形",
    "ja": "伝統的な",
    "ex_en": "Natto is a traditional Japanese food.",
    "ex_ja": "納豆は日本の伝統食です。",
    "memo": "名詞はtradition（伝統）"
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "musical",
    "answer": "musical",
    "ipa": "[ˈmjuːzɪkl]",
    "pos": "形",
    "ja": "音楽の",
    "ex_en": "She comes from a musical family.",
    "ex_ja": "彼女の家は音楽一家です。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "instrument",
    "answer": "instrument",
    "ipa": "[ˈɪnstrəmənt]",
    "pos": "名",
    "ja": "器具、楽器",
    "ex_en": "Do you play a musical instrument?",
    "ex_ja": "何か楽器やってる？",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "little",
    "answer": "little",
    "ipa": "[ˈlɪtl]",
    "pos": "名",
    "ja": "少しの量",
    "ex_en": "Do you know about rugby? — Yes, I know a little.",
    "ex_ja": "ラグビーわかる？ — うん、少しなら。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "online",
    "answer": "online",
    "ipa": "[ˌɑːnˈlaɪn]",
    "pos": "副",
    "ja": "オンラインで",
    "ex_en": "I bought this soccer ball online.",
    "ex_ja": "このサッカーボールはネットで買いました。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "gift",
    "answer": "gift",
    "ipa": "[gɪft]",
    "pos": "名",
    "ja": "贈り物",
    "ex_en": "We received a summer gift from Mr. Suzuki.",
    "ex_ja": "鈴木さんからお中元をいただきましたよ。",
    "memo": ""
  },
  {
    "lesson": "3-3",
    "part": "2",
    "en": "aunt",
    "answer": "aunt",
    "ipa": "[ænt]",
    "pos": "名",
    "ja": "おば",
    "ex_en": "This weekend, Aunt Hiroko is coming.",
    "ex_ja": "今週末、ヒロコおばさんが来るって。",
    "memo": ""
  },
  {
    "lesson": "3-4",
    "part": "3",
    "en": "who's",
    "answer": "who's",
    "ipa": "[huːz]",
    "pos": "短",
    "ja": "who is の短縮形",
    "ex_en": "Who's this on the right? — A yoga friend.",
    "ex_ja": "この右側の人だれ？ — ヨガ友達だよ。",
    "memo": ""
  },
  {
    "lesson": "3-4",
    "part": "3",
    "en": "character",
    "answer": "character",
    "ipa": "[ˈkærəktər]",
    "pos": "名",
    "ja": "性格、登場人物",
    "ex_en": "All the characters are bad people.",
    "ex_ja": "登場人物全員悪い人じゃん。",
    "memo": "characterはアクセントの位置に注意"
  },
  {
    "lesson": "3-4",
    "part": "3",
    "en": "him",
    "answer": "him",
    "ipa": "[hɪm]",
    "pos": "代",
    "ja": "彼を [に]",
    "ex_en": "Give this to him. — Who's 'him'?",
    "ex_ja": "これ、彼に渡して。 — 彼って？",
    "memo": ""
  },
  {
    "lesson": "3-4",
    "part": "3",
    "en": "very much",
    "answer": "very much",
    "ipa": "[—]",
    "pos": "句",
    "ja": "とても",
    "ex_en": "I like the feel of my cat very much.",
    "ex_ja": "うちのネコの触り心地がすごく好き。",
    "memo": ""
  },
  {
    "lesson": "3-4",
    "part": "3",
    "en": "nickname",
    "answer": "nickname",
    "ipa": "[ˈnɪkneɪm]",
    "pos": "名",
    "ja": "ニックネーム、あだ名",
    "ex_en": "Penny is a nickname for one cent coins.",
    "ex_ja": "ペニーは1セント硬貨のニックネームです。",
    "memo": ""
  },
  {
    "lesson": "3-4",
    "part": "3",
    "en": "idea",
    "answer": "idea",
    "ipa": "[aɪˈdiːə]",
    "pos": "名",
    "ja": "考え、案",
    "ex_en": "I have a good idea.",
    "ex_ja": "いいこと思いついた。",
    "memo": ""
  },
  {
    "lesson": "3-5",
    "part": "Goal Activity",
    "en": "maybe",
    "answer": "maybe",
    "ipa": "[ˈmeɪbi]",
    "pos": "副",
    "ja": "もしかすると",
    "ex_en": "Maybe I like him.",
    "ex_ja": "もしかしたらあの人のこと好きかも。",
    "memo": ""
  },
  {
    "lesson": "3-5",
    "part": "Goal Activity",
    "en": "carry",
    "answer": "carry",
    "ipa": "[ˈkæri]",
    "pos": "動",
    "ja": "運ぶ、持ち歩く",
    "ex_en": "Thanks. Do you always carry Band-Aids?",
    "ex_ja": "ありがとう。絆創膏いつも持ってるの？",
    "memo": ""
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "man",
    "answer": "man",
    "ipa": "[mæn]",
    "pos": "名",
    "ja": "男性",
    "ex_en": "Who is that man in a pink suit?",
    "ex_ja": "あのピンクのスーツ着た男の人はだれ？",
    "memo": ""
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "men",
    "answer": "men",
    "ipa": "[men]",
    "pos": "名",
    "ja": "man の複数形",
    "ex_en": "The main characters are three old men.",
    "ex_ja": "主人公は3人のおじさんです。",
    "memo": ""
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "excuse",
    "answer": "excuse",
    "ipa": "[ɪkˈskjuːz]",
    "pos": "動",
    "ja": "許す",
    "ex_en": "Please excuse my bad handwriting.",
    "ex_ja": "字が汚くてごめんなさい。",
    "memo": "名詞も excuse (言い訳)"
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "get to ~",
    "answer": "get to ~",
    "ipa": "[—]",
    "pos": "句",
    "ja": "〜に着く",
    "ex_en": "I usually get to school at 8:10.",
    "ex_ja": "私はふだん 8時10分に学校に着きます。",
    "memo": ""
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "then",
    "answer": "then",
    "ipa": "[ðen]",
    "pos": "副",
    "ja": "それから",
    "ex_en": "I ate potato chips, and then I did my homework.",
    "ex_ja": "ポテチを食べて、それから宿題をやりました。",
    "memo": ""
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "corner",
    "answer": "corner",
    "ipa": "[ˈkɔːrnər]",
    "pos": "名",
    "ja": "角、曲がり角",
    "ex_en": "Which corner do we turn at?",
    "ex_ja": "どの角を曲がるんだっけ？",
    "memo": ""
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "Thank you.",
    "answer": "Thank you.",
    "ipa": "[—]",
    "pos": "句",
    "ja": "ありがとう。",
    "ex_en": "Thank you, stranger!",
    "ex_ja": "だれかわからないけど、ありがとう！",
    "memo": ""
  },
  {
    "lesson": "3-6",
    "part": "Take Action! Talk 1",
    "en": "where's",
    "answer": "where's",
    "ipa": "[werz]",
    "pos": "短",
    "ja": "where is の短縮形",
    "ex_en": "Where's the can opener?",
    "ex_ja": "缶切りはどこですか？",
    "memo": ""
  },
  {
    "lesson": "4-1",
    "part": "Introduction",
    "en": "plan",
    "answer": "plan",
    "ipa": "[plæn]",
    "pos": "名",
    "ja": "計画",
    "ex_en": "Look, I made a study plan. What do you think?",
    "ex_ja": "見て、勉強計画作ってみた。どうよ。",
    "memo": "動詞も plan(計画を立てる)"
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "myself",
    "answer": "myself",
    "ipa": "[maɪˈself]",
    "pos": "代",
    "ja": "自分自身",
    "ex_en": "This is a treat for myself.",
    "ex_ja": "これは自分へのごほうび。",
    "memo": ""
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "last",
    "answer": "last",
    "ipa": "[læst]",
    "pos": "形",
    "ja": "最後の、この前の",
    "ex_en": "Aww. The last scene was too heartbreaking.",
    "ex_ja": "ああー。最後のシーンがつらすぎた。",
    "memo": "反対は first(最初の)"
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "Mt.",
    "answer": "Mt.",
    "ipa": "[maʊnt]",
    "pos": "名",
    "ja": "〜山",
    "ex_en": "Oh, I can see Mt. Fuji!",
    "ex_ja": "あ、富士山見えた！",
    "memo": "Mr.(男性への敬称) と混同しないように"
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "view",
    "answer": "view",
    "ipa": "[vjuː]",
    "pos": "名",
    "ja": "眺め",
    "ex_en": "The best view comes after the hardest climb.",
    "ex_ja": "最高の景色は、苦労して山を登った先にあるのです。",
    "memo": ""
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "top",
    "answer": "top",
    "ipa": "[tɑːp]",
    "pos": "名",
    "ja": "いちばん上の部分",
    "ex_en": "The can opener is in the top drawer.",
    "ex_ja": "缶切りはいちばん上の引き出しにあります。",
    "memo": ""
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "thick",
    "answer": "thick",
    "ipa": "[θɪk]",
    "pos": "形",
    "ja": "厚い、太い、濃い",
    "ex_en": "The soup is so thick.",
    "ex_ja": "スープが濃厚。",
    "memo": "反対は thin(薄い、細い)"
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "so",
    "answer": "so",
    "ipa": "[soʊ]",
    "pos": "副",
    "ja": "とても",
    "ex_en": "My dog is so fluffy.",
    "ex_ja": "うちの犬はとてもモコモコです。",
    "memo": "so is very より カジュアルだし感情入り"
  },
  {
    "lesson": "4-2",
    "part": "1",
    "en": "also",
    "answer": "also",
    "ipa": "[ˈɔːlsoʊ]",
    "pos": "副",
    "ja": "〜もまた",
    "ex_en": "I like manga, and I also like drawing.",
    "ex_ja": "ぼくは漫画が好きで、絵を描くのも好きです。",
    "memo": "too のほうが カジュアルな響き"
  },
  {
    "lesson": "4-3",
    "part": "2",
    "en": "Mr.",
    "answer": "Mr.",
    "ipa": "[ˈmɪstər]",
    "pos": "名",
    "ja": "〈男性に対して〉〜さん、〜先生",
    "ex_en": "Mr. Tanaka, please return to the teachers’ room.",
    "ex_ja": "田中先生、職員室へお戻りください。",
    "memo": ""
  },
  {
    "lesson": "4-3",
    "part": "2",
    "en": "Korean",
    "answer": "Korean",
    "ipa": "[kəˈriːən]",
    "pos": "形",
    "ja": "韓国の",
    "ex_en": "This Korean movie really hits home.",
    "ex_ja": "この韓国映画、めっちゃ刺さります。",
    "memo": "名詞は Korea(韓国)"
  },
  {
    "lesson": "4-3",
    "part": "2",
    "en": "hometown",
    "answer": "hometown",
    "ipa": "[ˈhoʊmtaʊn]",
    "pos": "名",
    "ja": "故郷",
    "ex_en": "My hometown is also along the coast, like here.",
    "ex_ja": "私の故郷の町も、ここみたいに海沿いです。",
    "memo": ""
  },
  {
    "lesson": "4-3",
    "part": "2",
    "en": "baby",
    "answer": "baby",
    "ipa": "[ˈbeɪbi]",
    "pos": "名",
    "ja": "赤ちゃん",
    "ex_en": "Look, a baby crab.",
    "ex_ja": "見て、カニの赤ちゃん。",
    "memo": ""
  },
  {
    "lesson": "4-3",
    "part": "2",
    "en": "cousin",
    "answer": "cousin",
    "ipa": "[ˈkʌzən]",
    "pos": "名",
    "ja": "いとこ",
    "ex_en": "Oh, does GariGari-kun have a cousin?",
    "ex_ja": "え、ガリガリ君っていとこがいるの？",
    "memo": ""
  },
  {
    "lesson": "4-3",
    "part": "2",
    "en": "cream cheese",
    "answer": "cream cheese",
    "ipa": "[kriːm tʃiːz]",
    "pos": "名",
    "ja": "クリームチーズ",
    "ex_en": "With extra cream cheese, please.",
    "ex_ja": "クリームチーズたっぷりめでお願いします。",
    "memo": ""
  },
  {
    "lesson": "4-4",
    "part": "Goal Activity",
    "en": "different",
    "answer": "different",
    "ipa": "[ˈdɪfrənt]",
    "pos": "形",
    "ja": "ちがった",
    "ex_en": "Today’s me is different from yesterday’s me.",
    "ex_ja": "今日のおれは昨日のおれとはちがうんだよ。",
    "memo": "名詞は difference(ちがい)"
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "topping",
    "answer": "topping",
    "ipa": "[ˈtɑːpɪŋ]",
    "pos": "名",
    "ja": "上に乗せるもの",
    "ex_en": "Could you add a soft-boiled egg as a topping?",
    "ex_ja": "トッピングで半熟卵をお願いできますか？",
    "memo": ""
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "boiled",
    "answer": "boiled",
    "ipa": "[bɔɪld]",
    "pos": "形",
    "ja": "ゆでた",
    "ex_en": "Do you want some boiled broccoli?",
    "ex_ja": "ゆでブロッコリー食べる？",
    "memo": "動詞は boil(ゆでる)"
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "boiled egg",
    "answer": "boiled egg",
    "ipa": "[bɔɪld eg]",
    "pos": "名",
    "ja": "ゆで卵",
    "ex_en": "The boiled egg exploded in the microwave.",
    "ex_ja": "ゆで卵が電子レンジで爆発した。",
    "memo": ""
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "garlic",
    "answer": "garlic",
    "ipa": "[ˈɡɑːrlɪk]",
    "pos": "名",
    "ja": "にんにく",
    "ex_en": "Now my hands smell like garlic.",
    "ex_ja": "手がにんにくの臭いになっちゃった。",
    "memo": ""
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "fried garlic",
    "answer": "fried garlic",
    "ipa": "[fraɪd ˈɡɑːrlɪk]",
    "pos": "名",
    "ja": "揚げたにんにく",
    "ex_en": "Without fried garlic, please.",
    "ex_ja": "揚げにんにくは抜きでお願いします。",
    "memo": ""
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "dollar",
    "answer": "dollar",
    "ipa": "[ˈdɑːlər]",
    "pos": "名",
    "ja": "〈貨幣の単位〉ドル",
    "ex_en": "Oh, there’s a dollar store over there.",
    "ex_ja": "あ、あそこ！ ドルショップがある。",
    "memo": ""
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "free",
    "answer": "free",
    "ipa": "[friː]",
    "pos": "形",
    "ja": "空いた、自由な、無料の",
    "ex_en": "Is this seat free? — Yes, go ahead.",
    "ex_ja": "この席あいてますか？ — はい、どうぞ。",
    "memo": ""
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "shrimp",
    "answer": "shrimp",
    "ipa": "[ʃrɪmp]",
    "pos": "名",
    "ja": "小エビ",
    "ex_en": "Do you like shrimp?",
    "ex_ja": "エビ好き？",
    "memo": ""
  },
  {
    "lesson": "4-5",
    "part": "Take Action! Listen 1",
    "en": "mixed",
    "answer": "mixed",
    "ipa": "[mɪkst]",
    "pos": "形",
    "ja": "混ざった",
    "ex_en": "This is Osaka’s famous mixed juice.",
    "ex_ja": "これが大阪名物ミックスジュースです。",
    "memo": "動詞は mix(混ぜる)"
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "clerk",
    "answer": "clerk",
    "ipa": "[klɜːrk]",
    "pos": "名",
    "ja": "店員",
    "ex_en": "That clerk is nice.",
    "ex_ja": "あの店員さんいいよね。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "What would you like?",
    "answer": "What would you like?",
    "ipa": "[—]",
    "pos": "句",
    "ja": "何になさいますか。",
    "ex_en": "What would you like? — I’d like ginger ale, please.",
    "ex_ja": "何になさいますか？ — ジンジャーエールをお願いします。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "I’d",
    "answer": "I’d",
    "ipa": "[aɪd]",
    "pos": "短",
    "ja": "I would の短縮形",
    "ex_en": "Hello, I’d like to order pizza for delivery.",
    "ex_ja": "もしもし、宅配ピザを注文したいのですが。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "would",
    "answer": "would",
    "ipa": "[wʊd]",
    "pos": "助",
    "ja": "will の過去形",
    "ex_en": "Would you like a bite?",
    "ex_ja": "一口食べる？",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "tuna",
    "answer": "tuna",
    "ipa": "[ˈtuːnə]",
    "pos": "名",
    "ja": "まぐろ",
    "ex_en": "I also love tuna sashimi.",
    "ex_ja": "マグロのお刺身も大好き。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "avocado",
    "answer": "avocado",
    "ipa": "[ˌævəˈkɑːdoʊ]",
    "pos": "名",
    "ja": "アボカド",
    "ex_en": "Ugh, this avocado is too soft.",
    "ex_ja": "うわ、このアボカドめっちゃぶよぶよ。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "anything",
    "answer": "anything",
    "ipa": "[ˈeniθɪŋ]",
    "pos": "代",
    "ja": "〈疑問文で〉何か、〈否定文で〉何も",
    "ex_en": "I don’t want to do anything today.",
    "ex_ja": "今日はなんにもしたくない。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "total",
    "answer": "total",
    "ipa": "[ˈtoʊtl]",
    "pos": "名",
    "ja": "合計",
    "ex_en": "Your total comes to $11.32.",
    "ex_ja": "合計11ドル32セントになります。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "pick",
    "answer": "pick",
    "ipa": "[pɪk]",
    "pos": "動",
    "ja": "つまみ取る、選ぶ",
    "ex_en": "Pick one from these.",
    "ex_ja": "この中から1こ選んで。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "pick up",
    "answer": "pick up",
    "ipa": "[—]",
    "pos": "句",
    "ja": "拾いあげる、取りにいく",
    "ex_en": "Pick up your socks there.",
    "ex_ja": "そこのくつしたを拾いなさい。",
    "memo": ""
  },
  {
    "lesson": "4-6",
    "part": "Take Action! Talk 2",
    "en": "order",
    "answer": "order",
    "ipa": "[ˈɔːrdər]",
    "pos": "名",
    "ja": "命令、注文",
    "ex_en": "Shall I take your order? — Yes, please.",
    "ex_ja": "ご注文をお伺いしましょうか？ — お願いします。",
    "memo": "動詞も order(命令、注文する)"
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "~'s",
    "answer": "~'s",
    "ipa": "[—]",
    "pos": "句",
    "ja": "〜の",
    "ex_en": "Ken's house has a nice porch.",
    "ex_ja": "ケンの家にはいい感じの縁側があります。",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "London",
    "answer": "London",
    "ipa": "[ˈlʌndən]",
    "pos": "名",
    "ja": "ロンドン",
    "ex_en": "In London, foxes often walk around the streets.",
    "ex_ja": "ロンドンではよく街中をきつねが歩いています。",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "tourist",
    "answer": "tourist",
    "ipa": "[ˈtʊərɪst]",
    "pos": "名",
    "ja": "観光客",
    "ex_en": "Are you a tourist or a local?",
    "ex_ja": "旅行者ですか？ それとも地元の方ですか？",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "place",
    "answer": "place",
    "ipa": "[pleɪs]",
    "pos": "名",
    "ja": "場所",
    "ex_en": "I'm afraid of high places.",
    "ex_ja": "私、高い所だめなのよ。",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "like",
    "answer": "like",
    "ipa": "[laɪk]",
    "pos": "前",
    "ja": "〜のような",
    "ex_en": "Life is like an onion. — What do you mean?",
    "ex_ja": "人生は玉ねぎみたいなものさ。— どういう意味？",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "they",
    "answer": "they",
    "ipa": "[ðeɪ]",
    "pos": "代",
    "ja": "彼(女)らは、それらは",
    "ex_en": "Are these your scissors? — Yes, they are.",
    "ex_ja": "これってきみのハサミ？ — そうだよ。",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "wear",
    "answer": "wear",
    "ipa": "[weər]",
    "pos": "動",
    "ja": "身に着けている",
    "ex_en": "Our vice principal wears round glasses.",
    "ex_ja": "うちの副校長先生は丸いメガネをかけています。",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "their",
    "answer": "their",
    "ipa": "[ðeər]",
    "pos": "代",
    "ja": "彼(女)らの、それらの",
    "ex_en": "I like their uniforms better than ours.",
    "ex_ja": "あいつのユニフォームのほうがいいな、ぼくらのより。",
    "memo": ""
  },
  {
    "lesson": "5-1",
    "part": "1",
    "en": "video",
    "answer": "video",
    "ipa": "[ˈvɪdioʊ]",
    "pos": "形",
    "ja": "動画の",
    "ex_en": "This video editing app is awesome.",
    "ex_ja": "この動画編集アプリめっちゃ優秀だわ。",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "does",
    "answer": "does",
    "ipa": "[dʌz]",
    "pos": "助",
    "ja": "do の 3人称単数現在形",
    "ex_en": "Lisa, does Mika like chocolate?",
    "ex_ja": "リサ、ミカってチョコ好き？",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "doesn't",
    "answer": "doesn't",
    "ipa": "[ˈdʌznt]",
    "pos": "短",
    "ja": "does not の短縮形",
    "ex_en": "This almond jelly doesn't have much taste.",
    "ex_ja": "この杏仁豆腐、あんまり味がしない。",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "page",
    "answer": "page",
    "ipa": "[peɪdʒ]",
    "pos": "名",
    "ja": "ページ",
    "ex_en": "Which page of the textbook is that on?",
    "ex_ja": "それって教科書の何ページ？",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "university",
    "answer": "university",
    "ipa": "[ˌjuːnəˈvɜːrsəti]",
    "pos": "名",
    "ja": "大学",
    "ex_en": "Should I go to university or not?",
    "ex_ja": "大学に行くべきかな、それとも行かないほうがいいのかな？",
    "memo": "university は総合大学 college は単科大学"
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "guitarist",
    "answer": "guitarist",
    "ipa": "[ɡɪˈtɑːrɪst]",
    "pos": "名",
    "ja": "ギター奏者",
    "ex_en": "I heard that the band is recruiting a guitarist.",
    "ex_ja": "軽音部がギタリスト募集してるんだって。",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "bagpipes",
    "answer": "bagpipes",
    "ipa": "[ˈbæɡpaɪps]",
    "pos": "名",
    "ja": "バグパイプ",
    "ex_en": "What do bagpipes sound like?",
    "ex_ja": "バグパイプってどんな音？",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "Scotland",
    "answer": "Scotland",
    "ipa": "[ˈskɑːtlənd]",
    "pos": "名",
    "ja": "スコットランド",
    "ex_en": "Scotland is a country in the United Kingdom.",
    "ex_ja": "スコットランドはイギリスの中の国の1つです。",
    "memo": "形容詞は Scottish (スコットランドの)"
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "them",
    "answer": "them",
    "ipa": "[ðem]",
    "pos": "代",
    "ja": "彼(女)らを[に]、それらを[に]",
    "ex_en": "Where are my glasses? — I saw them somewhere.",
    "ex_ja": "メガネはどこだ？ — どこかで見ましたよ。",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "concert",
    "answer": "concert",
    "ipa": "[ˈkɑːnsərt]",
    "pos": "名",
    "ja": "演奏会",
    "ex_en": "The concert is in three days. I can't wait!",
    "ex_ja": "コンサートまであと3日。楽しみ！",
    "memo": ""
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "performance",
    "answer": "performance",
    "ipa": "[pərˈfɔːrməns]",
    "pos": "名",
    "ja": "演技、上演",
    "ex_en": "Do not take photos during the performance.",
    "ex_ja": "公演中の写真撮影はご遠慮ください。",
    "memo": "動詞は perform (演じる)"
  },
  {
    "lesson": "5-2",
    "part": "2",
    "en": "internet",
    "answer": "internet",
    "ipa": "[ˈɪntərnet]",
    "pos": "名",
    "ja": "〈the をつけて〉インターネット",
    "ex_en": "Oh no, the internet isn't working again.",
    "ex_ja": "もー、またネットがつながらない。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "bye",
    "answer": "bye",
    "ipa": "[baɪ]",
    "pos": "間",
    "ja": "さようなら、じゃあね",
    "ex_en": "I'll call you back later. Bye.",
    "ex_ja": "後ほどまたお電話いたします。失礼します。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "tomorrow",
    "answer": "tomorrow",
    "ipa": "[təˈmɑːroʊ]",
    "pos": "副",
    "ja": "明日",
    "ex_en": "What day is it tomorrow? — Thursday.",
    "ex_ja": "明日って何曜日？ — 木曜日。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "wait",
    "answer": "wait",
    "ipa": "[weɪt]",
    "pos": "動",
    "ja": "待つ",
    "ex_en": "Wait, that's feed for the goldfish.",
    "ex_ja": "待って、それは金魚のエサだよ。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "whose",
    "answer": "whose",
    "ipa": "[huːz]",
    "pos": "代",
    "ja": "だれの",
    "ex_en": "Whose turn is it? — Not mine.",
    "ex_ja": "だれの番？ — 私じゃないよ。",
    "memo": "who's (= who is) と混同しないように"
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "towel",
    "answer": "towel",
    "ipa": "[ˈtaʊəl]",
    "pos": "名",
    "ja": "タオル",
    "ex_en": "Wipe your hands with a towel, not on your pants.",
    "ex_ja": "手はタオルでふきなさい、ズボンじゃなくて。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "yours",
    "answer": "yours",
    "ipa": "[jʊərz]",
    "pos": "代",
    "ja": "あなた(たち)のもの",
    "ex_en": "Is this pencil case yours? It was on the shoe locker.",
    "ex_ja": "この筆箱きみの？ くつ箱の上にあったよ。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "mine",
    "answer": "mine",
    "ipa": "[maɪn]",
    "pos": "代",
    "ja": "私のもの",
    "ex_en": "Here is your chicken salad. — Oh, that's mine.",
    "ex_ja": "こちらはチキンサラダです。— あ、それ私のです。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "hers",
    "answer": "hers",
    "ipa": "[hɜːrz]",
    "pos": "代",
    "ja": "彼女のもの",
    "ex_en": "It must be Yui. This handwriting is hers.",
    "ex_ja": "絶対ユイだよ。この字は彼女のだもん。",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "bottle",
    "answer": "bottle",
    "ipa": "[ˈbɑːtl]",
    "pos": "名",
    "ja": "びん",
    "ex_en": "What kind of waste is a bottle cap?",
    "ex_ja": "びんのふたつて何ゴミ？",
    "memo": "動詞も bottle (びんに詰める)"
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "water bottle",
    "answer": "water bottle",
    "ipa": "[ˈwɔːtər ˈbɑːtl]",
    "pos": "名",
    "ja": "水筒",
    "ex_en": "Oops, the ball just hit my water bottle!",
    "ex_ja": "わ、ボールが水筒に直撃した！",
    "memo": ""
  },
  {
    "lesson": "5-3",
    "part": "3",
    "en": "key",
    "answer": "key",
    "ipa": "[kiː]",
    "pos": "名",
    "ja": "鍵",
    "ex_en": "The key to creativity is curiosity.",
    "ex_ja": "創造性への鍵は好奇心である。",
    "memo": ""
  },
  {
    "lesson": "5-4",
    "part": "Small Talk",
    "en": "cheerful",
    "answer": "cheerful",
    "ipa": "[ˈtʃɪərfəl]",
    "pos": "形",
    "ja": "元気のいい、明るい",
    "ex_en": "Hey Siri, play some cheerful music, please.",
    "ex_ja": "ヘイ Siri、なにか明るい音楽かけて。",
    "memo": ""
  },
  {
    "lesson": "5-4",
    "part": "Small Talk",
    "en": "clever",
    "answer": "clever",
    "ipa": "[ˈklevər]",
    "pos": "形",
    "ja": "利口な",
    "ex_en": "My smartphone is so clever.",
    "ex_ja": "私のスマホはなんてかしこいんだ。",
    "memo": ""
  },
  {
    "lesson": "5-4",
    "part": "Small Talk",
    "en": "easygoing",
    "answer": "easygoing",
    "ipa": "[ˌiːziˈɡoʊɪŋ]",
    "pos": "形",
    "ja": "のんびりした",
    "ex_en": "Am I easygoing? Do you think so?",
    "ex_ja": "私ってのんびりしてる？ そうかな？",
    "memo": ""
  },
  {
    "lesson": "5-4",
    "part": "Small Talk",
    "en": "gentle",
    "answer": "gentle",
    "ipa": "[ˈdʒentl]",
    "pos": "形",
    "ja": "穏やかな、優しい",
    "ex_en": "The wind is gentle today.",
    "ex_ja": "今日は風が優しいです。",
    "memo": ""
  },
  {
    "lesson": "5-4",
    "part": "Small Talk",
    "en": "honest",
    "answer": "honest",
    "ipa": "[ˈɑːnəst]",
    "pos": "形",
    "ja": "正直な、誠実な",
    "ex_en": "I want to be an honest adult.",
    "ex_ja": "正直な大人になりたい。",
    "memo": "honest の下線部は発音しない"
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "series",
    "answer": "series",
    "ipa": "[ˈsɪriːz]",
    "pos": "名",
    "ja": "〈本や番組などの〉連続もの",
    "ex_en": "Life is a series of choices.",
    "ex_ja": "人生は選択の連続じゃ。",
    "memo": ""
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "detective",
    "answer": "detective",
    "ipa": "[dɪˈtektɪv]",
    "pos": "名",
    "ja": "探偵",
    "ex_en": "Are you a detective or something?",
    "ex_ja": "あなたは探偵か何かですか？",
    "memo": ""
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "thing",
    "answer": "thing",
    "ipa": "[θɪŋ]",
    "pos": "名",
    "ja": "もの、こと",
    "ex_en": "I can enjoy every little thing.",
    "ex_ja": "私はどんな小さなことでも楽しめます。",
    "memo": ""
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "carefully",
    "answer": "carefully",
    "ipa": "[ˈkerfəli]",
    "pos": "副",
    "ja": "注意深く",
    "ex_en": "Listen carefully and answer the questions.",
    "ex_ja": "よく聞いて、質問に答えなさい。",
    "memo": "形容詞は careful (注意深い)"
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "strange",
    "answer": "strange",
    "ipa": "[streɪndʒ]",
    "pos": "形",
    "ja": "奇妙な",
    "ex_en": "This bathroom cleaner smells strange.",
    "ex_ja": "このおふろの洗剤、変な臭いする。",
    "memo": ""
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "fact",
    "answer": "fact",
    "ipa": "[fækt]",
    "pos": "名",
    "ja": "事実",
    "ex_en": "Which are facts and which are opinions?",
    "ex_ja": "どれが事実でどれが意見だ？",
    "memo": ""
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "solve",
    "answer": "solve",
    "ipa": "[sɑːlv]",
    "pos": "動",
    "ja": "解く",
    "ex_en": "I can't solve this quiz.",
    "ex_ja": "このクイズが解けません。",
    "memo": "名詞は solution (解決)"
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "difficult",
    "answer": "difficult",
    "ipa": "[ˈdɪfɪkəlt]",
    "pos": "形",
    "ja": "難しい",
    "ex_en": "Is the high school entrance exam difficult?",
    "ex_ja": "高校入試って難しいですか？",
    "memo": "反対は easy (簡単な)"
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "problem",
    "answer": "problem",
    "ipa": "[ˈprɑːbləm]",
    "pos": "名",
    "ja": "問題",
    "ex_en": "The math test was okay. The problem is English.",
    "ex_ja": "数学のテストはなんとか大丈夫だった。問題は英語だよ。",
    "memo": ""
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "well-known",
    "answer": "well-known",
    "ipa": "[ˌwel ˈnoʊn]",
    "pos": "形",
    "ja": "よく知られた",
    "ex_en": "This is a well-known butcher in town.",
    "ex_ja": "ここは町でよく知られているお肉屋さんです。",
    "memo": ""
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "tough",
    "answer": "tough",
    "ipa": "[tʌf]",
    "pos": "形",
    "ja": "たくましい、〈状況が〉つらい",
    "ex_en": "I know it's tough, but hang in there. I'm with you.",
    "ex_ja": "大変だろうけどがんばって。応援してる。",
    "memo": "tough の下線部は f の発音"
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "confident",
    "answer": "confident",
    "ipa": "[ˈkɑːnfɪdənt]",
    "pos": "形",
    "ja": "自信のある",
    "ex_en": "I'm not confident. — Me, neither.",
    "ex_ja": "自信ないよ。— 私もない。",
    "memo": "名詞は confidence (自信)"
  },
  {
    "lesson": "5-5",
    "part": "Goal Activity",
    "en": "mysterious",
    "answer": "mysterious",
    "ipa": "[mɪˈstɪriəs]",
    "pos": "形",
    "ja": "神秘的な、謎めいた",
    "ex_en": "A mysterious scroll appeared from the closet.",
    "ex_ja": "押入れから謎の巻物が出てきた。",
    "memo": "名詞は mystery (謎)"
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "some",
    "answer": "some",
    "ipa": "[sʌm]",
    "pos": "形",
    "ja": "いくつかの、いくらかの",
    "ex_en": "Do you want some ketchup?",
    "ex_ja": "ケチャップいる？",
    "memo": ""
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "reminder",
    "answer": "reminder",
    "ipa": "[rɪˈmaɪndər]",
    "pos": "名",
    "ja": "思い出させるもの、通知",
    "ex_en": "Hey Siri, set a reminder to do my homework.",
    "ex_ja": "ヘイ Siri、宿題をするリマインダーをセットして。",
    "memo": ""
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "during",
    "answer": "during",
    "ipa": "[ˈdʊrɪŋ]",
    "pos": "前",
    "ja": "〈時を表して〉〜の間に",
    "ex_en": "Do not talk during the exam.",
    "ex_ja": "試験中におしゃべりしてはいけません。",
    "memo": ""
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "each",
    "answer": "each",
    "ipa": "[iːtʃ]",
    "pos": "形",
    "ja": "それぞれの",
    "ex_en": "There is a restroom on each floor.",
    "ex_ja": "お手洗いは各階にございます。",
    "memo": ""
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "throw",
    "answer": "throw",
    "ipa": "[θroʊ]",
    "pos": "名",
    "ja": "投げること、投球",
    "ex_en": "His throw to second base is amazing.",
    "ex_ja": "あいつのセカンドへの送球すごいなあ。",
    "memo": ""
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "disturb",
    "answer": "disturb",
    "ipa": "[dɪˈstɜːrb]",
    "pos": "動",
    "ja": "妨げる",
    "ex_en": "Please don't disturb me while I'm taking a nap.",
    "ex_ja": "昼寝をしているときに邪魔しないでください。",
    "memo": ""
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "clap",
    "answer": "clap",
    "ipa": "[klæp]",
    "pos": "動",
    "ja": "手をたたく",
    "ex_en": "Come on, clap your hands!",
    "ex_ja": "さあ、手拍子を！",
    "memo": "名詞は clapping (手をたたくこと)"
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "any",
    "answer": "any",
    "ipa": "[ˈeni]",
    "pos": "形",
    "ja": "〈肯定文で〉どの〜でも",
    "ex_en": "You can use any ball, I have eleven.",
    "ex_ja": "どのボールを使ってもええぞ、11こあるからな。",
    "memo": "any のあとに使う数えられる名詞は単数形で"
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "personal",
    "answer": "personal",
    "ipa": "[ˈpɜːrsənl]",
    "pos": "形",
    "ja": "個人的な",
    "ex_en": "Hey, that's my personal information.",
    "ex_ja": "こら、それはおれの個人情報だ。",
    "memo": ""
  },
  {
    "lesson": "5-6",
    "part": "Take Action! Listen 2",
    "en": "seat",
    "answer": "seat",
    "ipa": "[siːt]",
    "pos": "名",
    "ja": "座席",
    "ex_en": "I got a floor seat! — Wow! I'm jealous!",
    "ex_ja": "アリーナ席取れた！ — え！ いいなー！",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "boy",
    "answer": "boy",
    "ipa": "[bɔɪ]",
    "pos": "",
    "ja": "男の子",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "girl",
    "answer": "girl",
    "ipa": "[ɡɜːrl]",
    "pos": "",
    "ja": "女の子",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "friend",
    "answer": "friend",
    "ipa": "[frɛnd]",
    "pos": "",
    "ja": "友だち",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "classmate",
    "answer": "classmate",
    "ipa": "[ˈklæsmeɪt]",
    "pos": "",
    "ja": "同級生",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "teacher",
    "answer": "teacher",
    "ipa": "[ˈtitʃər]",
    "pos": "",
    "ja": "先生",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "player",
    "answer": "player",
    "ipa": "[ˈpleɪər]",
    "pos": "",
    "ja": "競技者",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "father",
    "answer": "father",
    "ipa": "[ˈfɑːðər]",
    "pos": "",
    "ja": "父",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "mother",
    "answer": "mother",
    "ipa": "[ˈmʌðər]",
    "pos": "",
    "ja": "母",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "brother",
    "answer": "brother",
    "ipa": "[ˈbrʌðər]",
    "pos": "",
    "ja": "兄、弟",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "sister",
    "answer": "sister",
    "ipa": "[ˈsɪstər]",
    "pos": "",
    "ja": "姉、妹",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "family",
    "answer": "family",
    "ipa": "[ˈfæməli]",
    "pos": "",
    "ja": "家族",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "人",
    "en": "everyone",
    "answer": "everyone",
    "ipa": "[ˈɛvriwʌn]",
    "pos": "",
    "ja": "みんな",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動物",
    "en": "dog",
    "answer": "dog",
    "ipa": "[dɔːɡ]",
    "pos": "",
    "ja": "イヌ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動物",
    "en": "cat",
    "answer": "cat",
    "ipa": "[kæt]",
    "pos": "",
    "ja": "ネコ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動物",
    "en": "bird",
    "answer": "bird",
    "ipa": "[bɜːrd]",
    "pos": "",
    "ja": "鳥",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動物",
    "en": "animal",
    "answer": "animal",
    "ipa": "[ˈænɪməl]",
    "pos": "",
    "ja": "動物",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "curry",
    "answer": "curry",
    "ipa": "[ˈkɜːri]",
    "pos": "",
    "ja": "カレー料理",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "rice",
    "answer": "rice",
    "ipa": "[raɪs]",
    "pos": "",
    "ja": "米",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "bread",
    "answer": "bread",
    "ipa": "[brɛd]",
    "pos": "",
    "ja": "パン",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "pizza",
    "answer": "pizza",
    "ipa": "[ˈpiːtsə]",
    "pos": "",
    "ja": "ピザ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "cake",
    "answer": "cake",
    "ipa": "[keɪk]",
    "pos": "",
    "ja": "ケーキ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "milk",
    "answer": "milk",
    "ipa": "[mɪlk]",
    "pos": "",
    "ja": "牛乳",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "coffee",
    "answer": "coffee",
    "ipa": "[ˈkɔːfi]",
    "pos": "",
    "ja": "コーヒー",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "食べ物・飲み物",
    "en": "tea",
    "answer": "tea",
    "ipa": "[tiː]",
    "pos": "",
    "ja": "茶",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "pen",
    "answer": "pen",
    "ipa": "[pen]",
    "pos": "",
    "ja": "ペン",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "pencil",
    "answer": "pencil",
    "ipa": "[ˈpensl]",
    "pos": "",
    "ja": "えんぴつ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "book",
    "answer": "book",
    "ipa": "[bʊk]",
    "pos": "",
    "ja": "本",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "notebook",
    "answer": "notebook",
    "ipa": "[ˈnoʊtbʊk]",
    "pos": "",
    "ja": "ノート",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "textbook",
    "answer": "textbook",
    "ipa": "[ˈtekstbʊk]",
    "pos": "",
    "ja": "教科書",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "dictionary",
    "answer": "dictionary",
    "ipa": "[ˈdɪkʃəneri]",
    "pos": "",
    "ja": "辞書",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "newspaper",
    "answer": "newspaper",
    "ipa": "[ˈnuːzpeɪpər]",
    "pos": "",
    "ja": "新聞",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "computer",
    "answer": "computer",
    "ipa": "[kəmˈpjuːtər]",
    "pos": "",
    "ja": "コンピュータ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "TV",
    "answer": "TV",
    "ipa": "[ˈtiːˈviː]",
    "pos": "",
    "ja": "テレビ(放送)",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "game",
    "answer": "game",
    "ipa": "[ɡeɪm]",
    "pos": "",
    "ja": "遊び、試合",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "piano",
    "answer": "piano",
    "ipa": "[piˈænoʊ]",
    "pos": "",
    "ja": "ピアノ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "guitar",
    "answer": "guitar",
    "ipa": "[ɡɪˈtɑːr]",
    "pos": "",
    "ja": "ギター",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "picture",
    "answer": "picture",
    "ipa": "[ˈpɪktʃər]",
    "pos": "",
    "ja": "絵、写真",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "map",
    "answer": "map",
    "ipa": "[mæp]",
    "pos": "",
    "ja": "地図",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "umbrella",
    "answer": "umbrella",
    "ipa": "[ʌmˈbrelə]",
    "pos": "",
    "ja": "かさ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "present",
    "answer": "present",
    "ipa": "[ˈpreznt]",
    "pos": "",
    "ja": "プレゼント",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "flower",
    "answer": "flower",
    "ipa": "[ˈflaʊər]",
    "pos": "",
    "ja": "花",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "bag",
    "answer": "bag",
    "ipa": "[bæɡ]",
    "pos": "",
    "ja": "ふくろ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "chair",
    "answer": "chair",
    "ipa": "[tʃeər]",
    "pos": "",
    "ja": "いす",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "desk",
    "answer": "desk",
    "ipa": "[desk]",
    "pos": "",
    "ja": "机",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "table",
    "answer": "table",
    "ipa": "[ˈteɪbl]",
    "pos": "",
    "ja": "テーブル",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "bed",
    "answer": "bed",
    "ipa": "[bed]",
    "pos": "",
    "ja": "ベッド",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "clothes",
    "answer": "clothes",
    "ipa": "[kloʊðz]",
    "pos": "",
    "ja": "衣服",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "bike",
    "answer": "bike",
    "ipa": "[baɪk]",
    "pos": "",
    "ja": "自転車",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "bus",
    "answer": "bus",
    "ipa": "[bʌs]",
    "pos": "",
    "ja": "バス",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "train",
    "answer": "train",
    "ipa": "[treɪn]",
    "pos": "",
    "ja": "電車",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "身の回りのもの",
    "en": "airplane",
    "answer": "airplane",
    "ipa": "[ˈɛərpleɪn]",
    "pos": "",
    "ja": "飛行機",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "classroom",
    "answer": "classroom",
    "ipa": "[ˈklæsruːm]",
    "pos": "",
    "ja": "教室",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "school",
    "answer": "school",
    "ipa": "[skuːl]",
    "pos": "",
    "ja": "学校",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "house",
    "answer": "house",
    "ipa": "[haʊs]",
    "pos": "",
    "ja": "家",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "town",
    "answer": "town",
    "ipa": "[taʊn]",
    "pos": "",
    "ja": "町",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "park",
    "answer": "park",
    "ipa": "[pɑːrk]",
    "pos": "",
    "ja": "公園",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "zoo",
    "answer": "zoo",
    "ipa": "[zuː]",
    "pos": "",
    "ja": "動物園",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "shop",
    "answer": "shop",
    "ipa": "[ʃɑːp]",
    "pos": "",
    "ja": "店",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "library",
    "answer": "library",
    "ipa": "[ˈlaɪbreri]",
    "pos": "",
    "ja": "図書館",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "bookstore",
    "answer": "bookstore",
    "ipa": "[ˈbʊkstoːr]",
    "pos": "",
    "ja": "本屋",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "station",
    "answer": "station",
    "ipa": "[ˈsteɪʃn]",
    "pos": "",
    "ja": "駅",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "restaurant",
    "answer": "restaurant",
    "ipa": "[ˈrestərɑːnt]",
    "pos": "",
    "ja": "レストラン",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "museum",
    "answer": "museum",
    "ipa": "[mjuːˈziːəm]",
    "pos": "",
    "ja": "博物館",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "hospital",
    "answer": "hospital",
    "ipa": "[ˈhɑːspɪtl]",
    "pos": "",
    "ja": "病院",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "street",
    "answer": "street",
    "ipa": "[striːt]",
    "pos": "",
    "ja": "通り",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "way",
    "answer": "way",
    "ipa": "[weɪ]",
    "pos": "",
    "ja": "道",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "subway",
    "answer": "subway",
    "ipa": "[ˈsʌbweɪ]",
    "pos": "",
    "ja": "地下鉄",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "bridge",
    "answer": "bridge",
    "ipa": "[brɪdʒ]",
    "pos": "",
    "ja": "橋",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "home",
    "answer": "home",
    "ipa": "[hoʊm]",
    "pos": "",
    "ja": "家庭、家",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "場所",
    "en": "country",
    "answer": "country",
    "ipa": "[ˈkʌntri]",
    "pos": "",
    "ja": "国",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "自然",
    "en": "sea",
    "answer": "sea",
    "ipa": "[siː]",
    "pos": "",
    "ja": "海",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "自然",
    "en": "beach",
    "answer": "beach",
    "ipa": "[biːtʃ]",
    "pos": "",
    "ja": "浜、海辺",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "自然",
    "en": "tree",
    "answer": "tree",
    "ipa": "[triː]",
    "pos": "",
    "ja": "木",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "自然",
    "en": "mountain",
    "answer": "mountain",
    "ipa": "[ˈmaʊntn]",
    "pos": "",
    "ja": "山",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "自然",
    "en": "river",
    "answer": "river",
    "ipa": "[ˈrɪvər]",
    "pos": "",
    "ja": "川",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "自然",
    "en": "lake",
    "answer": "lake",
    "ipa": "[leɪk]",
    "pos": "",
    "ja": "湖",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "自然",
    "en": "nature",
    "answer": "nature",
    "ipa": "[ˈneɪtʃər]",
    "pos": "",
    "ja": "自然",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "教科",
    "en": "English",
    "answer": "English",
    "ipa": "[ˈɪŋɡlɪʃ]",
    "pos": "",
    "ja": "英語",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "教科",
    "en": "Japanese",
    "answer": "Japanese",
    "ipa": "[ˌdʒæpəˈniːz]",
    "pos": "",
    "ja": "国語",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "教科",
    "en": "math",
    "answer": "math",
    "ipa": "[mæθ]",
    "pos": "",
    "ja": "数学",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "教科",
    "en": "subject",
    "answer": "subject",
    "ipa": "[ˈsʌbdʒɪkt]",
    "pos": "",
    "ja": "教科",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "スポーツ",
    "en": "soccer",
    "answer": "soccer",
    "ipa": "[ˈsɑːkər]",
    "pos": "",
    "ja": "サッカー",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "スポーツ",
    "en": "tennis",
    "answer": "tennis",
    "ipa": "[ˈtenɪs]",
    "pos": "",
    "ja": "テニス",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "スポーツ",
    "en": "baseball",
    "answer": "baseball",
    "ipa": "[ˈbeɪsbɔːl]",
    "pos": "",
    "ja": "野球",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "スポーツ",
    "en": "basketball",
    "answer": "basketball",
    "ipa": "[ˈbæskɪtbɔːl]",
    "pos": "",
    "ja": "バスケットボール",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "スポーツ",
    "en": "swimming",
    "answer": "swimming",
    "ipa": "[ˈswɪmɪŋ]",
    "pos": "",
    "ja": "水泳",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "スポーツ",
    "en": "sport",
    "answer": "sport",
    "ipa": "[spɔːrt]",
    "pos": "",
    "ja": "スポーツ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "スポーツ",
    "en": "team",
    "answer": "team",
    "ipa": "[tiːm]",
    "pos": "",
    "ja": "チーム",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "name",
    "answer": "name",
    "ipa": "[neɪm]",
    "pos": "",
    "ja": "名前",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "homework",
    "answer": "homework",
    "ipa": "[ˈhoʊmwɜːrk]",
    "pos": "",
    "ja": "宿題",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "class",
    "answer": "class",
    "ipa": "[klæs]",
    "pos": "",
    "ja": "クラス",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "club",
    "answer": "club",
    "ipa": "[klʌb]",
    "pos": "",
    "ja": "クラブ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "number",
    "answer": "number",
    "ipa": "[ˈnʌmbər]",
    "pos": "",
    "ja": "数",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "color",
    "answer": "color",
    "ipa": "[ˈkʌlər]",
    "pos": "",
    "ja": "色",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "morning",
    "answer": "morning",
    "ipa": "[ˈmɔːrnɪŋ]",
    "pos": "",
    "ja": "朝",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "afternoon",
    "answer": "afternoon",
    "ipa": "[ˌæftərˈnuːn]",
    "pos": "",
    "ja": "午後",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "evening",
    "answer": "evening",
    "ipa": "[ˈiːvnɪŋ]",
    "pos": "",
    "ja": "夕方、晩",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "night",
    "answer": "night",
    "ipa": "[naɪt]",
    "pos": "",
    "ja": "夜",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "day",
    "answer": "day",
    "ipa": "[deɪ]",
    "pos": "",
    "ja": "日",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "week",
    "answer": "week",
    "ipa": "[wiːk]",
    "pos": "",
    "ja": "週",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "month",
    "answer": "month",
    "ipa": "[mʌnθ]",
    "pos": "",
    "ja": "月",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "season",
    "answer": "season",
    "ipa": "[ˈsiːzn]",
    "pos": "",
    "ja": "季節",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "year",
    "answer": "year",
    "ipa": "[jɪr]",
    "pos": "",
    "ja": "年",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "date",
    "answer": "date",
    "ipa": "[deɪt]",
    "pos": "",
    "ja": "日付",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "time",
    "answer": "time",
    "ipa": "[taɪm]",
    "pos": "",
    "ja": "時間",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "breakfast",
    "answer": "breakfast",
    "ipa": "[ˈbrekfəst]",
    "pos": "",
    "ja": "朝食",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "lunch",
    "answer": "lunch",
    "ipa": "[lʌntʃ]",
    "pos": "",
    "ja": "昼食",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "dinner",
    "answer": "dinner",
    "ipa": "[ˈdɪnər]",
    "pos": "",
    "ja": "夕食",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "bath",
    "answer": "bath",
    "ipa": "[bæθ]",
    "pos": "",
    "ja": "入浴",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "birthday",
    "answer": "birthday",
    "ipa": "[ˈbɜːrθdeɪ]",
    "pos": "",
    "ja": "誕生日",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "vacation",
    "answer": "vacation",
    "ipa": "[veɪˈkeɪʃn]",
    "pos": "",
    "ja": "休暇",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "festival",
    "answer": "festival",
    "ipa": "[ˈfestɪvl]",
    "pos": "",
    "ja": "祭り",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "event",
    "answer": "event",
    "ipa": "[ɪˈvent]",
    "pos": "",
    "ja": "出来事、行事",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "life",
    "answer": "life",
    "ipa": "[laɪf]",
    "pos": "",
    "ja": "生命",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "job",
    "answer": "job",
    "ipa": "[dʒɑːb]",
    "pos": "",
    "ja": "職",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "trip",
    "answer": "trip",
    "ipa": "[trɪp]",
    "pos": "",
    "ja": "旅行",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "fun",
    "answer": "fun",
    "ipa": "[fʌn]",
    "pos": "",
    "ja": "楽しみ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "dream",
    "answer": "dream",
    "ipa": "[driːm]",
    "pos": "",
    "ja": "夢",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "memory",
    "answer": "memory",
    "ipa": "[ˈmeməri]",
    "pos": "",
    "ja": "記憶",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "future",
    "answer": "future",
    "ipa": "[ˈfjuːtʃər]",
    "pos": "",
    "ja": "未来",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "weather",
    "answer": "weather",
    "ipa": "[ˈweðər]",
    "pos": "",
    "ja": "天気",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "その他いろいろな名詞",
    "en": "world",
    "answer": "world",
    "ipa": "[wɜːrld]",
    "pos": "",
    "ja": "世界",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "be",
    "answer": "be",
    "ipa": "[biː]",
    "pos": "",
    "ja": "～である",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "want",
    "answer": "want",
    "ipa": "[wɑːnt]",
    "pos": "",
    "ja": "ほしいと思う",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "have",
    "answer": "have",
    "ipa": "[hæv]",
    "pos": "",
    "ja": "持っている",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "like",
    "answer": "like",
    "ipa": "[laɪk]",
    "pos": "",
    "ja": "好む",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "love",
    "answer": "love",
    "ipa": "[lʌv]",
    "pos": "",
    "ja": "愛する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "play",
    "answer": "play",
    "ipa": "[pleɪ]",
    "pos": "",
    "ja": "（競技などを）する、演奏する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "practice",
    "answer": "practice",
    "ipa": "[ˈpræktɪs]",
    "pos": "",
    "ja": "練習する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "study",
    "answer": "study",
    "ipa": "[ˈstʌdi]",
    "pos": "",
    "ja": "勉強する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "teach",
    "answer": "teach",
    "ipa": "[tiːtʃ]",
    "pos": "",
    "ja": "教える",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "read",
    "answer": "read",
    "ipa": "[riːd]",
    "pos": "",
    "ja": "読む",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "write",
    "answer": "write",
    "ipa": "[raɪt]",
    "pos": "",
    "ja": "書く",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "listen",
    "answer": "listen",
    "ipa": "[ˈlɪsn]",
    "pos": "",
    "ja": "聞く",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "speak",
    "answer": "speak",
    "ipa": "[spiːk]",
    "pos": "",
    "ja": "話す",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "talk",
    "answer": "talk",
    "ipa": "[tɔːk]",
    "pos": "",
    "ja": "会話する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "draw",
    "answer": "draw",
    "ipa": "[drɔː]",
    "pos": "",
    "ja": "（線画を）描く",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "look",
    "answer": "look",
    "ipa": "[lʊk]",
    "pos": "",
    "ja": "目を向ける",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "watch",
    "answer": "watch",
    "ipa": "[wɑːtʃ]",
    "pos": "",
    "ja": "注意して見る",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "see",
    "answer": "see",
    "ipa": "[siː]",
    "pos": "",
    "ja": "目に入る",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "meet",
    "answer": "meet",
    "ipa": "[miːt]",
    "pos": "",
    "ja": "会う",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "eat",
    "answer": "eat",
    "ipa": "[iːt]",
    "pos": "",
    "ja": "食べる",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "drink",
    "answer": "drink",
    "ipa": "[drɪŋk]",
    "pos": "",
    "ja": "飲む",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "cook",
    "answer": "cook",
    "ipa": "[kʊk]",
    "pos": "",
    "ja": "料理する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "make",
    "answer": "make",
    "ipa": "[meɪk]",
    "pos": "",
    "ja": "作る",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "clean",
    "answer": "clean",
    "ipa": "[kliːn]",
    "pos": "",
    "ja": "掃除する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "wash",
    "answer": "wash",
    "ipa": "[wɑːʃ]",
    "pos": "",
    "ja": "洗う",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "stand",
    "answer": "stand",
    "ipa": "[stænd]",
    "pos": "",
    "ja": "立つ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "walk",
    "answer": "walk",
    "ipa": "[wɔːk]",
    "pos": "",
    "ja": "歩く",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "run",
    "answer": "run",
    "ipa": "[rʌn]",
    "pos": "",
    "ja": "走る",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "swim",
    "answer": "swim",
    "ipa": "[swɪm]",
    "pos": "",
    "ja": "泳ぐ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "enjoy",
    "answer": "enjoy",
    "ipa": "[ɪnˈdʒɔɪ]",
    "pos": "",
    "ja": "楽しむ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "use",
    "answer": "use",
    "ipa": "[juːz]",
    "pos": "",
    "ja": "使う",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "ride",
    "answer": "ride",
    "ipa": "[raɪd]",
    "pos": "",
    "ja": "乗る",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "buy",
    "answer": "buy",
    "ipa": "[baɪ]",
    "pos": "",
    "ja": "買う",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "try",
    "answer": "try",
    "ipa": "[traɪ]",
    "pos": "",
    "ja": "試みる",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "help",
    "answer": "help",
    "ipa": "[help]",
    "pos": "",
    "ja": "手伝う",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "take",
    "answer": "take",
    "ipa": "[teɪk]",
    "pos": "",
    "ja": "持っていく",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "live",
    "answer": "live",
    "ipa": "[lɪv]",
    "pos": "",
    "ja": "住んでいる",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "go",
    "answer": "go",
    "ipa": "[ɡoʊ]",
    "pos": "",
    "ja": "行く",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "leave",
    "answer": "leave",
    "ipa": "[liːv]",
    "pos": "",
    "ja": "去る",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "turn",
    "answer": "turn",
    "ipa": "[tɜːrn]",
    "pos": "",
    "ja": "曲がる",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "visit",
    "answer": "visit",
    "ipa": "[ˈvɪzɪt]",
    "pos": "",
    "ja": "訪れる",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "travel",
    "answer": "travel",
    "ipa": "[ˈtrævl]",
    "pos": "",
    "ja": "旅行する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "know",
    "answer": "know",
    "ipa": "[noʊ]",
    "pos": "",
    "ja": "知っている",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "think",
    "answer": "think",
    "ipa": "[θɪŋk]",
    "pos": "",
    "ja": "思う",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "状態や動作を表すことば",
    "en": "guess",
    "answer": "guess",
    "ipa": "[ɡes]",
    "pos": "",
    "ja": "推測する",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "happy",
    "answer": "happy",
    "ipa": "[ˈhæpi]",
    "pos": "",
    "ja": "幸せな",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "sad",
    "answer": "sad",
    "ipa": "[sæd]",
    "pos": "",
    "ja": "悲しい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "busy",
    "answer": "busy",
    "ipa": "[ˈbɪzi]",
    "pos": "",
    "ja": "忙しい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "tired",
    "answer": "tired",
    "ipa": "[ˈtaɪərd]",
    "pos": "",
    "ja": "疲れた",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "hungry",
    "answer": "hungry",
    "ipa": "[ˈhʌŋɡri]",
    "pos": "",
    "ja": "空腹な",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "sleepy",
    "answer": "sleepy",
    "ipa": "[ˈsliːpi]",
    "pos": "",
    "ja": "眠い",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "good",
    "answer": "good",
    "ipa": "[ɡʊd]",
    "pos": "",
    "ja": "よい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "nice",
    "answer": "nice",
    "ipa": "[naɪs]",
    "pos": "",
    "ja": "すてきな、よい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "kind",
    "answer": "kind",
    "ipa": "[kaɪnd]",
    "pos": "",
    "ja": "親切な",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "big",
    "answer": "big",
    "ipa": "[bɪɡ]",
    "pos": "",
    "ja": "大きい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "large",
    "answer": "large",
    "ipa": "[lɑːrdʒ]",
    "pos": "",
    "ja": "広い、大きい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "small",
    "answer": "small",
    "ipa": "[smɔːl]",
    "pos": "",
    "ja": "小さい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "new",
    "answer": "new",
    "ipa": "[nuː]",
    "pos": "",
    "ja": "新しい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "old",
    "answer": "old",
    "ipa": "[oʊld]",
    "pos": "",
    "ja": "古い、年をとった",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "hot",
    "answer": "hot",
    "ipa": "[hɑːt]",
    "pos": "",
    "ja": "熱い、暑い",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "cold",
    "answer": "cold",
    "ipa": "[koʊld]",
    "pos": "",
    "ja": "冷たい、寒い",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "long",
    "answer": "long",
    "ipa": "[lɔːŋ]",
    "pos": "",
    "ja": "長い",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "short",
    "answer": "short",
    "ipa": "[ʃɔːrt]",
    "pos": "",
    "ja": "短い",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "easy",
    "answer": "easy",
    "ipa": "[ˈiːzi]",
    "pos": "",
    "ja": "簡単な",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "difficult",
    "answer": "difficult",
    "ipa": "[ˈdɪfɪkʌlt]",
    "pos": "",
    "ja": "難しい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "same",
    "answer": "same",
    "ipa": "[seɪm]",
    "pos": "",
    "ja": "同じ",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "different",
    "answer": "different",
    "ipa": "[ˈdɪfrənt]",
    "pos": "",
    "ja": "ちがう",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "cute",
    "answer": "cute",
    "ipa": "[kjuːt]",
    "pos": "",
    "ja": "かわいい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "beautiful",
    "answer": "beautiful",
    "ipa": "[ˈbjuːtɪfl]",
    "pos": "",
    "ja": "美しい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "wonderful",
    "answer": "wonderful",
    "ipa": "[ˈwʌndərfl]",
    "pos": "",
    "ja": "すばらしい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "interesting",
    "answer": "interesting",
    "ipa": "[ˈɪntrəstɪŋ]",
    "pos": "",
    "ja": "興味深い、おもしろい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "exciting",
    "answer": "exciting",
    "ipa": "[ɪkˈsaɪtɪŋ]",
    "pos": "",
    "ja": "興奮させるような",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "famous",
    "answer": "famous",
    "ipa": "[ˈfeɪməs]",
    "pos": "",
    "ja": "有名な",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "delicious",
    "answer": "delicious",
    "ipa": "[dɪˈlɪʃəs]",
    "pos": "",
    "ja": "とてもおいしい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "favorite",
    "answer": "favorite",
    "ipa": "[ˈfeɪvərɪt]",
    "pos": "",
    "ja": "一番好きな",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "best",
    "answer": "best",
    "ipa": "[best]",
    "pos": "",
    "ja": "最もよい",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "many",
    "answer": "many",
    "ipa": "[ˈmeni]",
    "pos": "",
    "ja": "多くの",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "名詞をくわしくできることば",
    "en": "all",
    "answer": "all",
    "ipa": "[ɔːl]",
    "pos": "",
    "ja": "すべての",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "very",
    "answer": "very",
    "ipa": "[ˈveri]",
    "pos": "",
    "ja": "とても",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "really",
    "answer": "really",
    "ipa": "[ˈriːəli]",
    "pos": "",
    "ja": "本当に",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "well",
    "answer": "well",
    "ipa": "[wel]",
    "pos": "",
    "ja": "上手に",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "hard",
    "answer": "hard",
    "ipa": "[hɑːrd]",
    "pos": "",
    "ja": "一生懸命に",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "fast",
    "answer": "fast",
    "ipa": "[fæst]",
    "pos": "",
    "ja": "速く",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "straight",
    "answer": "straight",
    "ipa": "[streɪt]",
    "pos": "",
    "ja": "まっすぐに",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "right",
    "answer": "right",
    "ipa": "[raɪt]",
    "pos": "",
    "ja": "右に",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "left",
    "answer": "left",
    "ipa": "[left]",
    "pos": "",
    "ja": "左に",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "here",
    "answer": "here",
    "ipa": "[hɪr]",
    "pos": "",
    "ja": "ここに[で]",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "together",
    "answer": "together",
    "ipa": "[təˈɡeðər]",
    "pos": "",
    "ja": "いっしょに",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "always",
    "answer": "always",
    "ipa": "[ˈɔːlweɪz]",
    "pos": "",
    "ja": "いつも",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "usually",
    "answer": "usually",
    "ipa": "[ˈjuːʒuəli]",
    "pos": "",
    "ja": "ふつうは",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "sometimes",
    "answer": "sometimes",
    "ipa": "[ˈsʌmtaɪmz]",
    "pos": "",
    "ja": "ときどき",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "never",
    "answer": "never",
    "ipa": "[ˈnevər]",
    "pos": "",
    "ja": "一度も～ない",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  },
  {
    "lesson": "elementary",
    "part": "動詞・形容詞をくわしくできることば",
    "en": "again",
    "answer": "again",
    "ipa": "[əˈɡen]",
    "pos": "",
    "ja": "もう一度",
    "ex_en": "",
    "ex_ja": "",
    "memo": ""
  }
];